###
GET http://localhost:8000/api/pacientes HTTP/1.1


###
POST http://localhost:8000/api/pacientes HTTP/1.1
Content-Type: application/json

{   
  "id_numeroCedula": "79978654",
  "nombre": "Interes",
  "apellido": "Villamil",
  "fecha_nacimiento":"2006-10-11",
  "telefono":"2234567"
}

###
GET http://localhost:8000/api/pacientes/79978654 HTTP/1.1

###
PUT http://localhost:8000/api/pacientes/79978654 HTTP/1.1
Content-Type: application/json

{
    "id_numeroCedula": "79978654",
    "nombre": "Andres",
    "apellido": "Villamil",
    "fecha_nacimiento":"2006-10-11",
    "telefono":"2234567"
  }

###
DELETE http://localhost:8000/api/pacientes/79978654 HTTP/1.1


###
GET http://localhost:8000/api/doctores HTTP/1.1

###
POST http://localhost:8000/api/doctores HTTP/1.1
Content-Type: application/json

{   
  "id_profesional": "71978654",
  "nombre": "Pepe",
  "apellido": "Perez",
  "correo":"pepe@mail.com",
  "telefono":"2234567",
  "especialidad": "medicina_interna"
}

###
GET http://localhost:8000/api/doctores/71978654 HTTP/1.1

###
PUT http://localhost:8000/api/doctores/71978654 HTTP/1.1
Content-Type: application/json

{
    "id_profesional": 71978654,
    "nombre": "Pepito",
    "apellido": "Perez",
    "correo": "pepe@mail.com",
    "telefono": "2234567",
    "especialidad": "medicina_interna"
  }

###
DELETE http://localhost:8000/api/doctores/71978654 HTTP/1.1
